### PR TITLE
Improve container build time in Getting Started document.

### PR DESCRIPTION
**Pull request by eengelking**
Updated the Dockerfile section to improve load time from ~7s to ~2s each time a change is made to code.

### CODE REVIEW

**Comment by cjellick** [comment]
@iwilltry42 can you test this and approve if it works?

**Comment by iwilltry42** [comment]
Hey @eengelking , thanks for this optimization!
It makes total sense the way the layering works, so that requirements don't have to be installed everytime something in the code is changed :+1: 
In the getting-started guide we also use the dev mode, which works around this for development by live-reloading code with Flask :)

**Review by iwilltry42 — APPROVED** [review]
LGTM

**Comment by eengelking** [comment]
> In the getting-started guide we also use the dev mode, which works around this for development by live-reloading code with Flask :)

@iwilltry42 In this usecase, I was using the `--dev` or `-i` flags, but I was updating the Acornfile `welcome` argument instead of the Python code directly. As a result, it doesn't allow the Flask live reload to be taken into consideration.  

Thank you for the approval. 👍

**Comment by cjellick** [comment]
Thanks @eengelking!

**Pull request merged**
