### PR TITLE
Prompt for Acorn install on run/dev if needed

### PR DESCRIPTION
**Pull request by iwilltry42**
- wraps call to Info() in installPrompt wrapper

Ref #515

### CODE REVIEW

**Comment by cjellick** [comment]
Your change is causing weird behavior for prebuilt images. It is causing acorn to ask me twice when I say no the first time:
```
acorn run ghcr.io/acorn-io/acorn-dns:v0.1.0
? Acorn is not installed, do you want to install it now?: No
? Acorn is not installed, do you want to install it now?: No
Error: no matches for kind "App" in version "api.acorn.io/v1"
```

Can you take a look and fix that?

**Comment by iwilltry42** [comment]
I'll take a look, thank you!
It should just exit if answered with "No", right? Doesn't make sense to continue trying if Acorn is not installed and the user denies installing it :man_shrugging:

**Comment by cjellick** [comment]
right.

Hit another problem (but one we might be able to ignore):
The test command i ran:
```
acorn run ghcr.io/acorn-io/acorn-dns:v0.1.0
```
never actually succeeds because that image require parameters (hence me saying in slack that we should have a hello-world image).

The problem is that the post-install checks get hung up on it. It sits here:
```
STATUS: ENDPOINTS[] HEALTHY[1/2] UPTODATE[2] [containers: default CrashLoopBackOff: back-off 2m40s restarting failed container=default pod=default-585f8d67c9-ljwc2_frosty-waterfall-45e4ba13-ad3(5fbdcbb9-5dc7-40b5-b043-b37e29c63726); frosty-waterfall is not ready]
STATUS: ENDPOINTS[] HEALTHY[1/2] UPTODATE[2] [containers: default Error: Exit Code 1; frosty-waterfall is not ready]
```

Must be some logic in the post-install check that is either waiting for the first app it finds to go healthy or for all apps it finds to go healthy. Can you look into this?

**Comment by iwilltry42** [comment]
@cjellick 

> It is causing acorn to ask me twice when I say no the first time

Fixed. It will now show an error if first one was answered with `No`: 
```bash
$ acorn run ghcr.io/acorn-io/acorn-dns:v0.1.0
? Acorn is not installed, do you want to install it now?: No
Error: no matches for kind "Info" in version "api.acorn.io/v1"
```

I was thinking to provide a prettier error, but that would require some refactorings deeper down in the prompt logic. Not sure if that's worth it, as it's pretty clear that the error is because Acorn is not installed?

> post-install checks get hung up on it.

Fixed. Actually they succeeded, but the progress indicator was still there because it was missing an `s.Success()`

**Comment by cjellick** [comment]
I don't see why we try the next action at all. Can we just abort if the user says no?

This change gives me the behavior I prefer:
```
diff --git a/pkg/client/ignore.go b/pkg/client/ignore.go
index 9185f64..e0af66c 100644
--- a/pkg/client/ignore.go
+++ b/pkg/client/ignore.go
@@ -3,6 +3,7 @@ package client
 import (
 	"context"
 	"errors"
+	"fmt"
 	"net"

 	"github.com/AlecAivazis/survey/v2"
@@ -40,6 +41,7 @@ func promptInstall[V any](ctx context.Context, f twoFunc[V]) (V, error) {
 			}
 			v, err = f()
 		}
+		return v, fmt.Errorf("action aborted. Acorn not installed")
 	}
 	return v, err
 }
```

Is there a reason we can't short circuit like this @ibuildthecloud ?

**Comment by cjellick** [comment]
let's not wait for @ibuildthecloud. we'll beg forgiveness later. If you amek this last change, I'll merge

**Comment by cjellick** [comment]
oh crud, that doesn't work. if you say yes, after the install for some reason it runs through that function again later and fails.

i guess that's what you were getting at

**Comment by cjellick** [comment]
Oh, seems like putting it in an else statement suffices:
```
+		} else {
+			return v, fmt.Errorf("action aborted. Acorn not installed")
 		}
 	}
```


PS, not trying to micromanage your PRs, I just dont know a lot of the areas of the code well because I didnt right them, so i have to get hands-on to grok whats going on

**Review by cjellick — CHANGES_REQUESTED** [review]
would like to see us short circuit if users says no to provide a better error message. see comments above.

**Comment by iwilltry42** [comment]
@cjellick  added else-statement as per your suggestion which results in a more informational error message.
Should we style that up with pterm?

**Comment by cjellick** [comment]
Seems fine to be as-is. I'm going to merge. If you want to do a follow up PR to pretty it up, fine by me. If not, also fine by me.

**Review by cjellick — APPROVED** [review]

**Pull request merged**
