### PR TITLE
Correct cli's pull command description text.

### PR DESCRIPTION
**Pull request by adebisi-fa**
Signed-off-by: ADEBISI Foluso A. <adebisi-fa@live.com>

### CODE REVIEW

**Comment by cjellick** [comment]
Thanks. This is going to fail our docs ci check because we require that the docs are generated from the cli.

Are you able to run
```
make gen-docs
```

and add the generated changes to the PR? If not, I can.

**Comment by adebisi-fa** [comment]
Done.

**Comment by cjellick** [comment]
thanks. rerunning the build, will merge after that.

FWIW, the DCO check fails because you didn't sign-off on the commit.

You sign-off on a commit by adding `-s` to the commit command:
```
git commit -s
```

Our intention is that that you sign-off on commits to indicate that you agree to the DCO.

Since this is a small change, it isn't a big deal; I can merge without you doing that, but just wanted to let you know why the DCO check on this PR fails.

I'll be adding a CONTRIBUTING.md to explain the DCO and what you'd be signing off on.

**Review by cjellick — APPROVED** [review]
manually marked DCO as passed

**Pull request merged**
