### PR TITLE
change: add namespace opt to tests and use user-provided ingress-class-name

### PR DESCRIPTION
**Pull request by iwilltry42**
Ref #659

### CODE REVIEW

**Comment by cjellick** [comment]
@iwilltry42 i dont fully understand the need for the test namespace. can you please epxlain?

Also, im going to nitpick your commit message a little. Can you follow these guidelines:
https://github.com/acorn-io/acorn/blob/main/CONTRIBUTING.md#commits

Mainly, i want good commit hygiene from us so that we can lead by example for later contributors

**Comment by iwilltry42** [comment]
Okay, I don't know what the hell happened here, but my rebase to change the wording somehow failed :thinking:

**Comment by iwilltry42** [comment]
> @iwilltry42 i dont fully understand the need for the test namespace. can you please epxlain?

`acorn check` could be run before `acorn install`, so the `acorn-system` namespace doesn't exist yet.
So the two options we have are a) create a namespace only for the checks and delete it again or b) let the user provide any existing namespace via that new flag.
I'd be happy with both.

**Comment by cjellick** [comment]
@ibuildthecloud can you please give your thoughts on this one?

**Review by cjellick — APPROVED** [review]

**Review by cjellick — APPROVED** [review]

**Pull request merged**
