### PR TITLE
Use Go's built-in DNS resolver to avoid DNS issues when building Acorns

### PR DESCRIPTION
**Pull request by g-linville**
### Checklist
- [x] The title of this PR would make a good line in Acorn's Release Note's Changelog
- [ ] The title of this PR ends with a link to the main issue being address in parentheses, like: `This is a title (#1216)`. [Here's an example](https://github.com/acorn-io/acorn/pull/1199)
- [ ] All relevant issues are referenced in the PR description. *NOTE: don't use [GitHub keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) that auto-close issues*
- [x] Commits follow [contributing guidance](https://github.com/acorn-io/acorn/blob/main/CONTRIBUTING.md#commits)
- [x] Automated tests added to cover the changes. If tests couldn't be added, an explanation is provided in the Verification and Testing section
- [x] Changes to user-facing functionality, API, CLI, and upgrade impacts are clearly called out in PR description
- [ ] PR has at least two approvals before merging (or a reasonable exception, like it's just a docs change)

### CODE REVIEW

**Comment by ibuildthecloud** [comment]
I don't think this makes any difference. AFAIK we are already using the pure go resolver because the binary is not linked to glibc at all (at least on linux).  I could be wrong, but if you get 
```
$ ldd bin/acorn 
	not a dynamic executable
```
I don't see how it could not be using pure go.

**Comment by cjellick** [comment]
oh wow. this 100% fixes it for me locally

**Comment by cjellick** [comment]
i didnt think you had to mess with `-tags netgo` anymore

**Comment by g-linville** [comment]
For me, on macOS, I never hit the issue with `-tags netgo`. I sometimes hit it without that. I agree that it's strange...

**Review by cjellick — APPROVED** [review]

**Review by thedadams — APPROVED** [review]

**Pull request merged**
