### PR TITLE
docs: fix registry reference in getting-started guide

### LINKED ISSUE #586: Suggestions to improve step 7 of the getting started doc section
After successfully completing the "getting started" section described in the doc, I'd like to share some feedback with you guys on step 7, as I had to struggle a bit. Some simple changes might help future folks quite a bit.

- There is no such thing as "my.registry.com". Now I know it's just a placeholder, but it wasn't apparent. This is especially important because the `acorn login` command does not report login failure, as I don't think it actually logs you in, making it impossible to know a good registry/credential combo from bad.
- It would have been great to spell out the commonly used registry URLs (ghcr.io is mentioned in `acorn login --help` but not in the docs, `docker.io` is not mentioned, I had to guess after failing with `hub.docker.com`)
- Different repo has different rules on tagging (I think). For example the docker.io repo would need the user name as part of the tag, so `acorn/getting-started` wouldn't work.

In any case, hope the above is helpful to you guys. And since I had it, let me also share with you an error message I had to ponder with. To you guys the cause of the problem might look obvious, but for someone not intimately familiar with the Kubernetes/docker world (which I think would be your target users), this might not be as easy to troubleshoot, especially when they have followed the docs to the letter.

```
$ acorn push my.registry.com/acorn/getting-started:v0.0.1
Error: Post "https://kubernetes.docker.internal:6443/apis/api.acorn.io/v1/namespaces/acorn/images/my.registry.com+acorn+getting-started:v0.0.1/push": stream error: stream ID 71; INTERNAL_ERROR; received from peer
```

### PR DESCRIPTION
**Pull request by iwilltry42**
Signed-off-by: Thorsten Klein <tk@thklein.io>

Ref: #586

### CODE REVIEW

**Review by cjellick — APPROVED** [review]

**Comment by cjellick** [comment]
@iwilltry42 can you add `git commit -s --amend` to add a sign-off?

**Comment by cjellick** [comment]
@iwilltry42 - Please dont do "Fixes <issue>".
I don't like auto-closing of issues.

**Comment by iwilltry42** [comment]
@cjellick rebased upon main and added signature

**Comment by cjellick** [comment]
ty

**Pull request merged**
