### PR TITLE
change: preserve the order of the choices in the prompt for imageallowrules scope

### PR DESCRIPTION
**Pull request by iwilltry42**
removed from the title: "incredibly ugly way to ..."

If you have any prettier idea to preserve the order as written in the maps, feel free to suggest :)
I couldn't find a simple way without writing some custom sorting function which seems overkill for this.

Ref #1715

### Checklist
- [x] The title of this PR would make a good line in Acorn's Release Note's Changelog
- [x] The title of this PR ends with a link to the main issue being address in parentheses, like: `This is a title (#1216)`. [Here's an example](https://github.com/acorn-io/acorn/pull/1199)
- [x] All relevant issues are referenced in the PR description. *NOTE: don't use [GitHub keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) that auto-close issues*
- [x] Commits follow [contributing guidance](https://github.com/acorn-io/acorn/blob/main/CONTRIBUTING.md#commits)
- [ ] Automated tests added to cover the changes. If tests couldn't be added, an explanation is provided in the Verification and Testing section
- [x] Changes to user-facing functionality, API, CLI, and upgrade impacts are clearly called out in PR description
- [ ] PR has at least two approvals before merging (or a reasonable exception, like it's just a docs change)

### CODE REVIEW

**Review by g-linville — APPROVED** [review]
I think it's fine. My only suggestion is to add a comment in the code explaining that it is formatted this way in order to preserve the order.

**Review by g-linville — APPROVED** [review]
I think it's fine. My only suggestion is to add a comment in the code explaining that it is formatted this way in order to preserve the order.

**Review by thedadams — APPROVED** [review]
I think this is fine.

Another possible approach would be to add a `Display` function/method in the `imageallowrules` package. The only advantage of this would be that you could construct the `choices` slice as a `[]imageallowrules.SimpleImageScope` and do do something like
```
for _, choice := range choices {
    choiceMap[choice.Display()] = string(choice)
}
```

Not sure if it is worth the trouble, but I know you were commenting how you didn't like this code 😅

**Comment by iwilltry42** [comment]
@g-linville I added a comment for clarity.
@thedadams I'll just close my eyes when scrolling past it in the future :)

**Pull request merged**
