### PR TITLE
go: rewrite interface{} as any

### PR DESCRIPTION
**Pull request by azazeal**
This PR rewrites instances of `interface{}` as `any`. It was generated with the help of `gofmt` and, more specifically, via executing `gofmt -w -r 'interface{} -> any' .` inside the root of the repository, manually excluding the following files (which look to be autogenerated):

- `pkg/apis/api.acorn.io/v1/conversion.go`
- `pkg/apis/internal.acorn.io/v1/map.go`
- `pkg/openapi/generated/openapi_generated.go`

As an added benefit, running `gofmt` also fixed the format of the following files:

* `pkg/cli/pull.go`
* `pkg/cli/secret_rm.go`
* `pkg/cli/start.go`
* `pkg/cli/stop.go`
* `pkg/cli/tag.go`
* `pkg/client/info.go`
* `pkg/version/version.go`

which were not properly formatted.

Signed-off-by: Panagiotis Siatras <azazeal@users.noreply.github.com>

### CODE REVIEW

**Comment by ibuildthecloud** [comment]
Oh cool, I was just thinking as I was removing references to ioutil that we should move everything to any. Thanks.

**Comment by azazeal** [comment]
Not quite sure what broke the build, might it be possible this is a flaky test? If so, could we rerun the build one more time, please?

**Comment by cjellick** [comment]
Github is 500ing on me, so I cannot see the build. But yeah, we started seeing a flaky test yesterday. If it's the same one, i'll rerun until we get a clean build.

@ibuildthecloud we probably need to dig further into that failure

**Comment by azazeal** [comment]
So, this is definetely a flaky test as it also broke #661 (which didn't touch any of the Go code) 😭

**Review by ibuildthecloud — APPROVED** [review]

**Review by ibuildthecloud — APPROVED** [review]

**Pull request merged**
